name: data-transfer
channels:
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bokeh=2.4.3=py37h89c1867_0
  - ca-certificates=2022.6.15=ha878542_0
  - click=8.1.3=py37h89c1867_0
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - cudatoolkit=11.7.0=hd8887f6_10
  - cupy=10.5.0=py37h17e6d27_0
  - cytoolz=0.11.2=py37h540881e_2
  - dask=2022.2.0=pyhd8ed1ab_0
  - dask-core=2022.2.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distributed=2022.2.0=py37h89c1867_0
  - fastrlock=0.8=py37hd23a5d3_2
  - freetype=2.10.4=h0708190_1
  - fsspec=2022.5.0=pyhd8ed1ab_0
  - giflib=5.2.1=h36c2ea0_2
  - heapdict=1.0.1=py_0
  - icu=70.1=h27087fc_0
  - importlib-metadata=4.11.4=py37h89c1867_0
  - ipython=7.33.0=py37h89c1867_0
  - jedi=0.18.1=py37h89c1867_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=15_linux64_openblas
  - libcblas=3.9.0=15_linux64_openblas
  - libdeflate=1.12=h166bdaf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - libhwloc=2.3.0=h5e5b7d1_1
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=15_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=hc85c160_1
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h22db469_0
  - libzlib=1.2.12=h166bdaf_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.1=py37h540881e_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py37h7cecad7_0
  - ncurses=6.3=h27087fc_1
  - numpy=1.21.6=py37h976b520_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.4=h166bdaf_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.5=py37he8f5f7f_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.1=py37h44f0d7a_1
  - pip=22.1.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.30=pyha770c72_0
  - psutil=5.9.1=py37h540881e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytz=2022.1=pyhd8ed1ab_0
  - pyyaml=6.0=py37h540881e_4
  - readline=8.1.2=h0f457ee_0
  - setuptools=59.8.0=py37h89c1867_1
  - six=1.16.0=pyh6c4a22f_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.39.0=h4ff8645_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - tornado=6.1=py37h540881e_3
  - traitlets=5.3.0=pyhd8ed1ab_0
  - typing_extensions=4.2.0=pyha770c72_1
  - ucx=1.12.0+gd367332=cuda11.2_0
  - ucx-proc=1.0.0=gpu
  - ucx-py=0.25.00=py37_gd367332_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_1
  - zstd=1.5.2=h8a70e8d_1
  - pip:
    - pynvml==11.4.1
